name: Clone

on:
  workflow_dispatch:
#  schedule:
#    - cron: 0 */12 * * *

jobs:
  Clone:
    runs-on: Ubuntu-20.04
    steps:
    - name: Clone
      uses: TobKed/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        upstream_repository: jason5ng32/MyIP
        upstream_branch: main
        target_repository: waynesg/IPCheck
        target_branch: main
        force: true
        tags: false
