name: sync

on:
  workflow_dispatch:
  watch:
    types: started
  # schedule:
  #   - cron: 0 20 * * *
  repository_dispatch:

jobs:
  Clone:
    runs-on: Ubuntu-20.04
    steps:
    - name: Clone
      uses: TobKed/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        upstream_repository: jason5ng32/MyIP
        upstream_branch: main
        target_repository: waynesg/IPCheck
        target_branch: main
        force: true
        tags: false
